/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'juliao15' at '10/22/16 3:36 PM' with Gradle 3.1
 *
 * @author juliao15, @date 10/22/16 3:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
